/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.EnderecoBeans;
import ModelBeans.PessoaBeans;
import ModelBeans.PessoaFisicaBeans;
import ModelBeans.PessoaJuridicaBeans;
import ModelBeans.TelefoneBeans;
import ModelConection.ConexaoBD;
import ModelDao.EnderecoDAO;
import ModelDao.PessoaDAO;
import ModelDao.PessoaFisicaDAO;
import ModelDao.PessoaJuridicaDAO;
import ModelDao.TelefoneDAO;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ander
 */
public class CadPessoa extends javax.swing.JFrame {

        PessoaBeans pessoaBeans = new PessoaBeans();
        EnderecoBeans enderecoBeans = new EnderecoBeans();
        PessoaJuridicaBeans pessoaJuridicaBeans = new PessoaJuridicaBeans();
        PessoaFisicaBeans pessoaFisicaBeans = new PessoaFisicaBeans();
        TelefoneBeans telefoneBeans = new TelefoneBeans();
        PessoaDAO controlPessoa = new PessoaDAO();
        EnderecoDAO controlEndereco = new EnderecoDAO();
        PessoaJuridicaDAO controlPessoaJuridica = new PessoaJuridicaDAO();
        PessoaFisicaDAO controlPessoaFisica = new PessoaFisicaDAO();
        TelefoneDAO controlTelefone = new TelefoneDAO();
        ConexaoBD conexaoBD = new ConexaoBD();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
    public CadPessoa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUf = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooserDataAdmissao = new com.toedter.calendar.JDateChooser();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCPFCNPJ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxTipoPessoa = new javax.swing.JComboBox();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldCep = new javax.swing.JTextField();
        jTextFieldCargo = new javax.swing.JTextField();
        jDateChooserDataNasc = new com.toedter.calendar.JDateChooser();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data de Nascimento:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 110, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(550, 40, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("CPF/CNPJ:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 110, 90, 20);

        jTextFieldUf.setEnabled(false);
        jPanel1.add(jTextFieldUf);
        jTextFieldUf.setBounds(420, 280, 40, 30);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(40, 70, 360, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Logradouro:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 180, 100, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("CEP:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 180, 40, 20);

        jDateChooserDataAdmissao.setEnabled(false);
        jPanel1.add(jDateChooserDataAdmissao);
        jDateChooserDataAdmissao.setBounds(380, 350, 170, 30);

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);
        jPanel1.add(jComboBoxSexo);
        jComboBoxSexo.setBounds(550, 70, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Rg:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 110, 30, 20);

        jTextFieldLogradouro.setEnabled(false);
        jPanel1.add(jTextFieldLogradouro);
        jTextFieldLogradouro.setBounds(260, 210, 310, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Telefone:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 110, 80, 20);

        jTextFieldSalario.setEnabled(false);
        jPanel1.add(jTextFieldSalario);
        jTextFieldSalario.setBounds(40, 350, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cargo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 320, 60, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Salário:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 320, 60, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Data de admissão:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 320, 150, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("UF:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(420, 250, 30, 20);

        jTextFieldCPFCNPJ.setEnabled(false);
        jPanel1.add(jTextFieldCPFCNPJ);
        jTextFieldCPFCNPJ.setBounds(220, 140, 210, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Cidade:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 250, 60, 20);

        jTextFieldBairro.setEnabled(false);
        jPanel1.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(200, 280, 210, 30);

        jTextFieldTelefone.setEnabled(false);
        jPanel1.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(600, 140, 150, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Bairro:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(200, 250, 60, 20);

        jTextFieldRG.setEnabled(false);
        jPanel1.add(jTextFieldRG);
        jTextFieldRG.setBounds(440, 140, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Numero:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 180, 70, 20);

        jTextFieldNumero.setEnabled(false);
        jPanel1.add(jTextFieldNumero);
        jTextFieldNumero.setBounds(590, 210, 80, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Tipo de pessoa:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(410, 40, 130, 20);

        jComboBoxTipoPessoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar", "Física", "Jurídica" }));
        jComboBoxTipoPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoPessoaItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxTipoPessoa);
        jComboBoxTipoPessoa.setBounds(410, 70, 130, 30);

        jTextFieldCidade.setEnabled(false);
        jPanel1.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(40, 280, 150, 30);

        jTextFieldCep.setEnabled(false);
        jPanel1.add(jTextFieldCep);
        jTextFieldCep.setBounds(40, 210, 210, 30);

        jTextFieldCargo.setEnabled(false);
        jPanel1.add(jTextFieldCargo);
        jTextFieldCargo.setBounds(200, 350, 170, 30);

        jDateChooserDataNasc.setEnabled(false);
        jPanel1.add(jDateChooserDataNasc);
        jDateChooserDataNasc.setBounds(40, 140, 170, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(620, 260, 90, 30);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(620, 320, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 760, 400);

        setSize(new java.awt.Dimension(805, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int idEndereco = 0,idPessoa = 0;
        String sexo = (String) jComboBoxSexo.getSelectedItem(); 
        String tipo = (String) jComboBoxTipoPessoa.getSelectedItem();
       
        //Cadastrar o endereco 
        enderecoBeans.setCep(jTextFieldCep.getText());
        enderecoBeans.setLogradouro(jTextFieldLogradouro.getText());
        enderecoBeans.setNumeroCasa(jTextFieldNumero.getText());
        enderecoBeans.setCidade(jTextFieldCidade.getText());
        enderecoBeans.setBairro(jTextFieldBairro.getText());
        enderecoBeans.setUf(jTextFieldUf.getText());
        idEndereco = controlEndereco.Salvar(enderecoBeans);
        
        //Cadastrar o pessoa
        pessoaBeans.setNome(jTextFieldNome.getText());
        if(tipo.equals("Física")){//fazendo a comparação se a pessoa é do tipo fisica ou juridica
            pessoaBeans.setTipo("F");
        }else{
            pessoaBeans.setTipo("J");
        }        
        if(sexo.equals("Masculino")){//fazendo a comparação do sexo
            pessoaBeans.setSexo("M");
        }else{
            pessoaBeans.setSexo("F");
        }
        if(jDateChooserDataNasc.getDate() == null){//para a pessoa juridica que não tem data de nascimento. esse if verifica se é nulo e adiciona uma data default
            try {
                pessoaBeans.setDataNasc(formato.parse("01/01/1900"));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"erro  "+ ex);
            }
        }else{
            pessoaBeans.setDataNasc(jDateChooserDataNasc.getDate());
        }        
        pessoaBeans.setEnd_cod(idEndereco);
        idPessoa = controlPessoa.Salvar(pessoaBeans);
        
        //Cadastrar o pessoa juridia
        if(tipo.equals("Jurídica")){
            pessoaJuridicaBeans.setCnpj(jTextFieldCPFCNPJ.getText());
            pessoaJuridicaBeans.setPes_cod(idPessoa);
            controlPessoaJuridica.Salvar(pessoaJuridicaBeans);
        }else{
            //Cadastrar o pessoa fisica
            pessoaFisicaBeans.setCpf(jTextFieldCPFCNPJ.getText());
            pessoaFisicaBeans.setCargo(jTextFieldCargo.getText());
            pessoaFisicaBeans.setRg(jTextFieldRG.getText());
            pessoaFisicaBeans.setDataAdmissao(jDateChooserDataAdmissao.getDate());
            pessoaFisicaBeans.setSalario(jTextFieldSalario.getText());
            pessoaFisicaBeans.setPes_cod(idPessoa);   
            controlPessoaFisica.Salvar(pessoaFisicaBeans);
        } 
        
        telefoneBeans.setTelefone(jTextFieldTelefone.getText());
        telefoneBeans.setPes_cod(idPessoa);
        controlTelefone.Salvar(telefoneBeans);       
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxTipoPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoPessoaItemStateChanged
        
        if(jComboBoxTipoPessoa.getSelectedItem().equals("Física")){
            jComboBoxSexo.setEnabled(true);
            jDateChooserDataNasc.setEnabled(true);
            jTextFieldCPFCNPJ.setEnabled(true);
            jTextFieldRG.setEnabled(true);
            jTextFieldTelefone.setEnabled(true);
            jTextFieldCep.setEnabled(true);
            jTextFieldLogradouro.setEnabled(true);
            jTextFieldNumero.setEnabled(true);
            jTextFieldCidade.setEnabled(true);
            jTextFieldBairro.setEnabled(true);
            jTextFieldUf.setEnabled(true);
            jTextFieldSalario.setEnabled(true);
            jTextFieldCargo.setEnabled(true);
            jDateChooserDataAdmissao.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            }else{
            jComboBoxSexo.setEnabled(false);
            jDateChooserDataNasc.setEnabled(false);
            jTextFieldCPFCNPJ.setEnabled(true);
            jTextFieldRG.setEnabled(false);
            jTextFieldTelefone.setEnabled(true);
            jTextFieldCep.setEnabled(true);
            jTextFieldLogradouro.setEnabled(true);
            jTextFieldNumero.setEnabled(true);
            jTextFieldCidade.setEnabled(true);
            jTextFieldBairro.setEnabled(true);
            jTextFieldUf.setEnabled(true);
            jTextFieldSalario.setEnabled(false);
            jTextFieldCargo.setEnabled(false);
            jDateChooserDataAdmissao.setEnabled(false);
            jButtonSalvar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            }
    }//GEN-LAST:event_jComboBoxTipoPessoaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxTipoPessoa;
    private com.toedter.calendar.JDateChooser jDateChooserDataAdmissao;
    private com.toedter.calendar.JDateChooser jDateChooserDataNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPFCNPJ;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUf;
    // End of variables declaration//GEN-END:variables
}
